package entity;
// Generated 28-Apr-2020 9:49:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Dossierpatient generated by hbm2java
 */
@Entity
@Table(name="DOSSIERPATIENT"
    ,schema="A18PROJET3"
    , uniqueConstraints = @UniqueConstraint(columnNames="NUMAS") 
)
public class Dossierpatient  implements java.io.Serializable {


     private BigDecimal numdos;
     private Docteur docteur;
     private String nomp;
     private String prenomp;
     private Character genre;
     private String numas;
     private Date datenaiss;
     private Date datec;
     private Set<Consultation> consultations = new HashSet<Consultation>(0);

    public Dossierpatient() {
    }

	
    public Dossierpatient(BigDecimal numdos, String nomp, String prenomp) {
        this.numdos = numdos;
        this.nomp = nomp;
        this.prenomp = prenomp;
    }
    public Dossierpatient(BigDecimal numdos, Docteur docteur, String nomp, String prenomp, Character genre, String numas, Date datenaiss, Date datec, Set<Consultation> consultations) {
       this.numdos = numdos;
       this.docteur = docteur;
       this.nomp = nomp;
       this.prenomp = prenomp;
       this.genre = genre;
       this.numas = numas;
       this.datenaiss = datenaiss;
       this.datec = datec;
       this.consultations = consultations;
    }
   
     @Id 

    
    @Column(name="NUMDOS", unique=true, nullable=false, precision=22, scale=0)
    public BigDecimal getNumdos() {
        return this.numdos;
    }
    
    public void setNumdos(BigDecimal numdos) {
        this.numdos = numdos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="MATRICULE")
    public Docteur getDocteur() {
        return this.docteur;
    }
    
    public void setDocteur(Docteur docteur) {
        this.docteur = docteur;
    }

    
    @Column(name="NOMP", nullable=false, length=50)
    public String getNomp() {
        return this.nomp;
    }
    
    public void setNomp(String nomp) {
        this.nomp = nomp;
    }

    
    @Column(name="PRENOMP", nullable=false, length=50)
    public String getPrenomp() {
        return this.prenomp;
    }
    
    public void setPrenomp(String prenomp) {
        this.prenomp = prenomp;
    }

    
    @Column(name="GENRE", length=1)
    public Character getGenre() {
        return this.genre;
    }
    
    public void setGenre(Character genre) {
        this.genre = genre;
    }

    
    @Column(name="NUMAS", unique=true, length=12)
    public String getNumas() {
        return this.numas;
    }
    
    public void setNumas(String numas) {
        this.numas = numas;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATENAISS", length=7)
    public Date getDatenaiss() {
        return this.datenaiss;
    }
    
    public void setDatenaiss(Date datenaiss) {
        this.datenaiss = datenaiss;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATEC", length=7)
    public Date getDatec() {
        return this.datec;
    }
    
    public void setDatec(Date datec) {
        this.datec = datec;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="dossierpatient")
    public Set<Consultation> getConsultations() {
        return this.consultations;
    }
    
    public void setConsultations(Set<Consultation> consultations) {
        this.consultations = consultations;
    }




}


