package entity;
// Generated 28-Apr-2020 9:49:00 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Medicaments generated by hbm2java
 */
@Entity
@Table(name="MEDICAMENTS"
    ,schema="A18PROJET3"
    , uniqueConstraints = @UniqueConstraint(columnNames="NOM") 
)
public class Medicaments  implements java.io.Serializable {


     private String id;
     private Categories categories;
     private String nom;
     private BigDecimal prix;
     private Set<Ordonnancemedicaments> ordonnancemedicamentses = new HashSet<Ordonnancemedicaments>(0);

    public Medicaments() {
    }

	
    public Medicaments(String id) {
        this.id = id;
    }
    public Medicaments(String id, Categories categories, String nom, BigDecimal prix, Set<Ordonnancemedicaments> ordonnancemedicamentses) {
       this.id = id;
       this.categories = categories;
       this.nom = nom;
       this.prix = prix;
       this.ordonnancemedicamentses = ordonnancemedicamentses;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, length=8)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CATEGORIE_ID")
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }

    
    @Column(name="NOM", unique=true, length=150)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="PRIX", precision=8)
    public BigDecimal getPrix() {
        return this.prix;
    }
    
    public void setPrix(BigDecimal prix) {
        this.prix = prix;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicaments")
    public Set<Ordonnancemedicaments> getOrdonnancemedicamentses() {
        return this.ordonnancemedicamentses;
    }
    
    public void setOrdonnancemedicamentses(Set<Ordonnancemedicaments> ordonnancemedicamentses) {
        this.ordonnancemedicamentses = ordonnancemedicamentses;
    }




}


