package entite;
// Generated 8-May-2020 12:51:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConsultationId generated by hbm2java
 */
@Embeddable
public class ConsultationId  implements java.io.Serializable {


     private int codedocteur;
     private long numdos;
     private Date datec;

    public ConsultationId() {
    }

    public ConsultationId(int codedocteur, long numdos, Date datec) {
       this.codedocteur = codedocteur;
       this.numdos = numdos;
       this.datec = datec;
    }
   


    @Column(name="CODEDOCTEUR", nullable=false, precision=8, scale=0)
    public int getCodedocteur() {
        return this.codedocteur;
    }
    
    public void setCodedocteur(int codedocteur) {
        this.codedocteur = codedocteur;
    }


    @Column(name="NUMDOS", nullable=false, precision=10, scale=0)
    public long getNumdos() {
        return this.numdos;
    }
    
    public void setNumdos(long numdos) {
        this.numdos = numdos;
    }


    @Column(name="DATEC", nullable=false, length=7)
    public Date getDatec() {
        return this.datec;
    }
    
    public void setDatec(Date datec) {
        this.datec = datec;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ConsultationId) ) return false;
		 ConsultationId castOther = ( ConsultationId ) other; 
         
		 return (this.getCodedocteur()==castOther.getCodedocteur())
 && (this.getNumdos()==castOther.getNumdos())
 && ( (this.getDatec()==castOther.getDatec()) || ( this.getDatec()!=null && castOther.getDatec()!=null && this.getDatec().equals(castOther.getDatec()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodedocteur();
         result = 37 * result + (int) this.getNumdos();
         result = 37 * result + ( getDatec() == null ? 0 : this.getDatec().hashCode() );
         return result;
   }   


}


