package entite;
// Generated 7-May-2020 8:57:20 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Consultation generated by hbm2java
 */
@Entity
@Table(name="CONSULTATION"
    ,schema="A18PROJET3"
)
public class Consultation  implements java.io.Serializable {


     private ConsultationId id;
     private Ordonnance ordonnance;
     private Docteur docteur;
     private Dossierpatient dossierpatient;
     private String diagnostic;

    public Consultation() {
    }

	
    public Consultation(ConsultationId id, Docteur docteur, Dossierpatient dossierpatient) {
        this.id = id;
        this.docteur = docteur;
        this.dossierpatient = dossierpatient;
    }
    public Consultation(ConsultationId id, Ordonnance ordonnance, Docteur docteur, Dossierpatient dossierpatient, String diagnostic) {
       this.id = id;
       this.ordonnance = ordonnance;
       this.docteur = docteur;
       this.dossierpatient = dossierpatient;
       this.diagnostic = diagnostic;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="codedocteur", column=@Column(name="CODEDOCTEUR", nullable=false, length=8) ), 
        @AttributeOverride(name="numdos", column=@Column(name="NUMDOS", nullable=false, length=16) ), 
        @AttributeOverride(name="datec", column=@Column(name="DATEC", nullable=false, length=7) ) } )
    public ConsultationId getId() {
        return this.id;
    }
    
    public void setId(ConsultationId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NUMORD")
    public Ordonnance getOrdonnance() {
        return this.ordonnance;
    }
    
    public void setOrdonnance(Ordonnance ordonnance) {
        this.ordonnance = ordonnance;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CODEDOCTEUR", nullable=false, insertable=false, updatable=false)
    public Docteur getDocteur() {
        return this.docteur;
    }
    
    public void setDocteur(Docteur docteur) {
        this.docteur = docteur;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NUMDOS", nullable=false, insertable=false, updatable=false)
    public Dossierpatient getDossierpatient() {
        return this.dossierpatient;
    }
    
    public void setDossierpatient(Dossierpatient dossierpatient) {
        this.dossierpatient = dossierpatient;
    }

    
    @Column(name="DIAGNOSTIC")
    public String getDiagnostic() {
        return this.diagnostic;
    }
    
    public void setDiagnostic(String diagnostic) {
        this.diagnostic = diagnostic;
    }




}


