package entite;
// Generated 8-May-2020 12:51:34 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Docteur generated by hbm2java
 */
@Entity
@Table(name="DOCTEUR"
    ,schema="A18PROJET3"
)
public class Docteur  implements java.io.Serializable {


     private int matricule;
     private Specialite specialite;
     private String nomm;
     private String prenomm;
     private String ville;
     private String adresse;
     private String niveau;
     private Short nbrpatients;
     private Set<Consultation> consultations = new HashSet<Consultation>(0);
     private Set<Dossierpatient> dossierpatients = new HashSet<Dossierpatient>(0);

    public Docteur() {
    }

	
    public Docteur(int matricule, String nomm, String prenomm) {
        this.matricule = matricule;
        this.nomm = nomm;
        this.prenomm = prenomm;
    }
    public Docteur(int matricule, Specialite specialite, String nomm, String prenomm, String ville, String adresse, String niveau, Short nbrpatients, Set<Consultation> consultations, Set<Dossierpatient> dossierpatients) {
       this.matricule = matricule;
       this.specialite = specialite;
       this.nomm = nomm;
       this.prenomm = prenomm;
       this.ville = ville;
       this.adresse = adresse;
       this.niveau = niveau;
       this.nbrpatients = nbrpatients;
       this.consultations = consultations;
       this.dossierpatients = dossierpatients;
    }
   
     @Id 

    
    @Column(name="MATRICULE", unique=true, nullable=false, precision=8, scale=0)
    public int getMatricule() {
        return this.matricule;
    }
    
    public void setMatricule(int matricule) {
        this.matricule = matricule;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="SPECIALITE")
    public Specialite getSpecialite() {
        return this.specialite;
    }
    
    public void setSpecialite(Specialite specialite) {
        this.specialite = specialite;
    }

    
    @Column(name="NOMM", nullable=false, length=20)
    public String getNomm() {
        return this.nomm;
    }
    
    public void setNomm(String nomm) {
        this.nomm = nomm;
    }

    
    @Column(name="PRENOMM", nullable=false, length=20)
    public String getPrenomm() {
        return this.prenomm;
    }
    
    public void setPrenomm(String prenomm) {
        this.prenomm = prenomm;
    }

    
    @Column(name="VILLE", length=20)
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }

    
    @Column(name="ADRESSE", length=50)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="NIVEAU", length=10)
    public String getNiveau() {
        return this.niveau;
    }
    
    public void setNiveau(String niveau) {
        this.niveau = niveau;
    }

    
    @Column(name="NBRPATIENTS", precision=3, scale=0)
    public Short getNbrpatients() {
        return this.nbrpatients;
    }
    
    public void setNbrpatients(Short nbrpatients) {
        this.nbrpatients = nbrpatients;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="docteur")
    public Set<Consultation> getConsultations() {
        return this.consultations;
    }
    
    public void setConsultations(Set<Consultation> consultations) {
        this.consultations = consultations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="docteur")
    public Set<Dossierpatient> getDossierpatients() {
        return this.dossierpatients;
    }
    
    public void setDossierpatients(Set<Dossierpatient> dossierpatients) {
        this.dossierpatients = dossierpatients;
    }




}


