package entite;
// Generated 8-May-2020 12:51:34 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Medicament generated by hbm2java
 */
@Entity
@Table(name="MEDICAMENT"
    ,schema="A18PROJET3"
    , uniqueConstraints = @UniqueConstraint(columnNames={"NOMMED", "CATEGORIE"}) 
)
public class Medicament  implements java.io.Serializable {


     private String idmed;
     private Categories categories;
     private String nommed;
     private BigDecimal prix;
     private Set<Ordonnancemedicaments> ordonnancemedicamentses = new HashSet<Ordonnancemedicaments>(0);

    public Medicament() {
    }

	
    public Medicament(String idmed, String nommed) {
        this.idmed = idmed;
        this.nommed = nommed;
    }
    public Medicament(String idmed, Categories categories, String nommed, BigDecimal prix, Set<Ordonnancemedicaments> ordonnancemedicamentses) {
       this.idmed = idmed;
       this.categories = categories;
       this.nommed = nommed;
       this.prix = prix;
       this.ordonnancemedicamentses = ordonnancemedicamentses;
    }
   
     @Id 

    
    @Column(name="IDMED", unique=true, nullable=false, length=8)
    public String getIdmed() {
        return this.idmed;
    }
    
    public void setIdmed(String idmed) {
        this.idmed = idmed;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CATEGORIE")
    public Categories getCategories() {
        return this.categories;
    }
    
    public void setCategories(Categories categories) {
        this.categories = categories;
    }

    
    @Column(name="NOMMED", nullable=false, length=150)
    public String getNommed() {
        return this.nommed;
    }
    
    public void setNommed(String nommed) {
        this.nommed = nommed;
    }

    
    @Column(name="PRIX", precision=8)
    public BigDecimal getPrix() {
        return this.prix;
    }
    
    public void setPrix(BigDecimal prix) {
        this.prix = prix;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="medicament")
    public Set<Ordonnancemedicaments> getOrdonnancemedicamentses() {
        return this.ordonnancemedicamentses;
    }
    
    public void setOrdonnancemedicamentses(Set<Ordonnancemedicaments> ordonnancemedicamentses) {
        this.ordonnancemedicamentses = ordonnancemedicamentses;
    }




}


