package entite;
// Generated 8-May-2020 12:51:34 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ordonnancemedicaments generated by hbm2java
 */
@Entity
@Table(name="ORDONNANCEMEDICAMENTS"
    ,schema="A18PROJET3"
)
public class Ordonnancemedicaments  implements java.io.Serializable {


     private OrdonnancemedicamentsId id;
     private Ordonnance ordonnance;
     private Medicament medicament;
     private Short nbboites;

    public Ordonnancemedicaments() {
    }

	
    public Ordonnancemedicaments(OrdonnancemedicamentsId id, Ordonnance ordonnance, Medicament medicament) {
        this.id = id;
        this.ordonnance = ordonnance;
        this.medicament = medicament;
    }
    public Ordonnancemedicaments(OrdonnancemedicamentsId id, Ordonnance ordonnance, Medicament medicament, Short nbboites) {
       this.id = id;
       this.ordonnance = ordonnance;
       this.medicament = medicament;
       this.nbboites = nbboites;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="numord", column=@Column(name="NUMORD", nullable=false, precision=8, scale=0) ), 
        @AttributeOverride(name="idmed", column=@Column(name="IDMED", nullable=false, length=8) ) } )
    public OrdonnancemedicamentsId getId() {
        return this.id;
    }
    
    public void setId(OrdonnancemedicamentsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NUMORD", nullable=false, insertable=false, updatable=false)
    public Ordonnance getOrdonnance() {
        return this.ordonnance;
    }
    
    public void setOrdonnance(Ordonnance ordonnance) {
        this.ordonnance = ordonnance;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDMED", nullable=false, insertable=false, updatable=false)
    public Medicament getMedicament() {
        return this.medicament;
    }
    
    public void setMedicament(Medicament medicament) {
        this.medicament = medicament;
    }

    
    @Column(name="NBBOITES", precision=3, scale=0)
    public Short getNbboites() {
        return this.nbboites;
    }
    
    public void setNbboites(Short nbboites) {
        this.nbboites = nbboites;
    }




}


