package entite;
// Generated 8-May-2020 12:51:34 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrdonnancechirurgieId generated by hbm2java
 */
@Embeddable
public class OrdonnancechirurgieId  implements java.io.Serializable {


     private int numord;
     private short rang;

    public OrdonnancechirurgieId() {
    }

    public OrdonnancechirurgieId(int numord, short rang) {
       this.numord = numord;
       this.rang = rang;
    }
   


    @Column(name="NUMORD", nullable=false, precision=8, scale=0)
    public int getNumord() {
        return this.numord;
    }
    
    public void setNumord(int numord) {
        this.numord = numord;
    }


    @Column(name="RANG", nullable=false, precision=3, scale=0)
    public short getRang() {
        return this.rang;
    }
    
    public void setRang(short rang) {
        this.rang = rang;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrdonnancechirurgieId) ) return false;
		 OrdonnancechirurgieId castOther = ( OrdonnancechirurgieId ) other; 
         
		 return (this.getNumord()==castOther.getNumord())
 && (this.getRang()==castOther.getRang());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNumord();
         result = 37 * result + this.getRang();
         return result;
   }   


}


