package entite;
// Generated 8-May-2020 12:51:34 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrdonnancemedicamentsId generated by hbm2java
 */
@Embeddable
public class OrdonnancemedicamentsId  implements java.io.Serializable {


     private int numord;
     private String idmed;

    public OrdonnancemedicamentsId() {
    }

    public OrdonnancemedicamentsId(int numord, String idmed) {
       this.numord = numord;
       this.idmed = idmed;
    }
   


    @Column(name="NUMORD", nullable=false, precision=8, scale=0)
    public int getNumord() {
        return this.numord;
    }
    
    public void setNumord(int numord) {
        this.numord = numord;
    }


    @Column(name="IDMED", nullable=false, length=8)
    public String getIdmed() {
        return this.idmed;
    }
    
    public void setIdmed(String idmed) {
        this.idmed = idmed;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrdonnancemedicamentsId) ) return false;
		 OrdonnancemedicamentsId castOther = ( OrdonnancemedicamentsId ) other; 
         
		 return (this.getNumord()==castOther.getNumord())
 && ( (this.getIdmed()==castOther.getIdmed()) || ( this.getIdmed()!=null && castOther.getIdmed()!=null && this.getIdmed().equals(castOther.getIdmed()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNumord();
         result = 37 * result + ( getIdmed() == null ? 0 : this.getIdmed().hashCode() );
         return result;
   }   


}


