package entite;
// Generated 8-May-2020 12:51:34 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ordonnancechirurgie generated by hbm2java
 */
@Entity
@Table(name="ORDONNANCECHIRURGIE"
    ,schema="A18PROJET3"
)
public class Ordonnancechirurgie  implements java.io.Serializable {


     private OrdonnancechirurgieId id;
     private Ordonnance ordonnance;
     private String nomchirurgie;

    public Ordonnancechirurgie() {
    }

	
    public Ordonnancechirurgie(OrdonnancechirurgieId id, Ordonnance ordonnance) {
        this.id = id;
        this.ordonnance = ordonnance;
    }
    public Ordonnancechirurgie(OrdonnancechirurgieId id, Ordonnance ordonnance, String nomchirurgie) {
       this.id = id;
       this.ordonnance = ordonnance;
       this.nomchirurgie = nomchirurgie;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="numord", column=@Column(name="NUMORD", nullable=false, precision=8, scale=0) ), 
        @AttributeOverride(name="rang", column=@Column(name="RANG", nullable=false, precision=3, scale=0) ) } )
    public OrdonnancechirurgieId getId() {
        return this.id;
    }
    
    public void setId(OrdonnancechirurgieId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="NUMORD", nullable=false, insertable=false, updatable=false)
    public Ordonnance getOrdonnance() {
        return this.ordonnance;
    }
    
    public void setOrdonnance(Ordonnance ordonnance) {
        this.ordonnance = ordonnance;
    }

    
    @Column(name="NOMCHIRURGIE", length=50)
    public String getNomchirurgie() {
        return this.nomchirurgie;
    }
    
    public void setNomchirurgie(String nomchirurgie) {
        this.nomchirurgie = nomchirurgie;
    }




}


