package entite;
// Generated 7-May-2020 8:57:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Specialites generated by hbm2java
 */
@Entity
@Table(name="SPECIALITES"
    ,schema="A18PROJET3"
    , uniqueConstraints = @UniqueConstraint(columnNames="TITRE") 
)
public class Specialites  implements java.io.Serializable {


     private byte code;
     private String titre;
     private String description;
     private Set<Docteur> docteurs = new HashSet<Docteur>(0);

    public Specialites() {
    }

	
    public Specialites(byte code) {
        this.code = code;
    }
    public Specialites(byte code, String titre, String description, Set<Docteur> docteurs) {
       this.code = code;
       this.titre = titre;
       this.description = description;
       this.docteurs = docteurs;
    }
   
     @Id 

    
    @Column(name="CODE", unique=true, nullable=false, precision=2, scale=0)
    public byte getCode() {
        return this.code;
    }
    
    public void setCode(byte code) {
        this.code = code;
    }

    
    @Column(name="TITRE", unique=true, length=100)
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }

    
    @Column(name="DESCRIPTION", length=500)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="specialites")
    public Set<Docteur> getDocteurs() {
        return this.docteurs;
    }
    
    public void setDocteurs(Set<Docteur> docteurs) {
        this.docteurs = docteurs;
    }




}


